version: '3'

services:
  skut-db-env:
    restart: always
    image: postgres:9.6.10-alpine
    container_name: skut_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: scutdb
    ports:
      - '5434:5432'
    volumes:
      - database:/var/lib/postgresql

  skut-api-env:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    container_name: skut_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
    - skut-db-env
    environment:
    - PYTHONUNBUFFERED=0

volumes:
  database:

